name: lib-user-manager-backend

on:
  push:
    branches: [ main ]

jobs:
  sonarqube:
    name: Analisis de codigo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      ##unit test
      # - name: Unit test
      #   run: cd autorizador && npm install && npm run test:ci
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        name: Ejecutando sonarqube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          git config --global user.email secrets.GIT_ACCOUNT
          git config --global user.name secrets.GIT_NAME
          npm install
          npm run build-publish
          git add .
          git commit -m "ci: Version updated [skip ci]"
          git push
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}